# Generated by Django 5.1.3 on 2024-11-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumber', '0002_alter_phonedevice_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedevice',
            name='method',
            field=models.CharField(choices=[('call', 'Phone Call'), ('sms', 'Text Message'), ('whatsapp', 'WhatsApp Message')], max_length=8, verbose_name='method'),
        ),
    ]
